### ISSUE TITLE
Получение ОМ по интерфейсу

### ISSUE THREAD

**Issue by alex912004** [nnx-framework/doctrine#1]
Создать метод для получения object manager по интерфейсу, чтобы не писать каждый раз получение имени ом.

**Comment by nnx-group** [comment]
Функционал реализован в рамках сервиса:
\Nnx\Doctrine\ObjectManager\ObjectManagerAutoDetectorInterface

Тесты:
\Nnx\Doctrine\ObjectManager\ObjectManagerAutoDetector
