### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by greabock** [nnx-framework/doctrine#16]
Очень понравилось решение с DiscriminatorEntry. Однако, не могу его использовать ввиду того, что ваше расширение устарело. Оно совсем умерло? )

**Comment by andrey-malofeykin** [comment]
Роман добрый день. Это решение разрабатывалось в рамках работ по созданию платформы для компании где я уже не работаю :-). По факту решение не поддерживается несколько лет. В принципе я могу вернуться к его поддержке, но это произойдет не раньше чем через месяц. К сожалению сейчас перегружен основной работой.

**Comment by greabock** [comment]
В принципе, я вижу как можно актуализировать часть про Discriminator. Но тут много еще всего (как по мне, совершенно лишнего, так как оно решает совсем другие задачи).
Не очень разбираюсь в лицензиях. Под GNU 3.0  можно просто скопипастить DiscriminatorEntryListener в рамках своего пакета (само собой, сославшись на вас в лицензии)?

**Comment by greabock** [comment]
Ах, да, я вижу... Автор исходника jasperkuperus, он об этом пост написал. Значит код совсем открытый... В любом случае, спасибо!
