### ISSUE TITLE
Кеширование карты сущностей

### ISSUE THREAD

**Issue by alex912004** [nnx-framework/doctrine#3]
Для построения кэша карты сущностей необходимо выполнить команду: php public/index.php entity-map build --objectManager=doctrine.entitymanager.orm_default

Предлагаю делать это автоматически,  при первом обращении. 
Так же добавить флажок enableCache: 
    если установлен в true - строим и используем кэш
    false - даже если кэш есть, не использовать его (необходимость при разработке)

**Comment by nnx-group** [comment]
Документация 
http://nnx-doctrine.readthedocs.org/ru/latest/auto-resolve-entity-class-name/
Тесты \Nnx\Doctrine\PhpUnit\Test\EntityManager\EntityMapAbstractFactoryFunctionalTest::testAutoBuildCache
