### ISSUE TITLE
Получение Repository по интерфейсу сущности

### ISSUE THREAD

**Issue by palexashkav** [nnx-framework/doctrine#5]
Нужен сервис для получения репозитория \Doctrine\Common\Persistence\ObjectRepository по интерфейсу сущности, т.к. в большинстве случаев, нужно не только создание сущности, но и работа с ней.

**Comment by old-town** [comment]
Реализовано в версии https://github.com/nnx-framework/doctrine/tree/0.1.19
Добавлен сервис \Nnx\Doctrine\Service\ObjectManagerServiceInterface
