### ISSUE TITLE
Default object manager name 

### ISSUE THREAD

**Issue by alex912004** [nnx-framework/doctrine#6]
Предлагаю установить 'doctrine.entitymanager.orm_default' как значение по умолчанию для \Nnx\Doctrine\ObjectManager\ObjectManagerNameProviderTrait::$objectManagerName,
т.к. данная возможность будет использоваться только в случае нескольких сервисов в одном приложении.

Чтобы не дублировать в конфигурациях большинства сервисов 
        Module::CONFIG_KEY => [
            'objectManagerName' => 'doctrine.entitymanager.orm_default'
        ]

**Comment by old-town** [comment]
Реализовано в 0.1.17
