### ISSUE TITLE
Нужна возможность получать Repository как по имени объекта, так и по имени интерфейса

### ISSUE THREAD

**Issue by palexashkav** [nnx-framework/doctrine#8]
\Nnx\Doctrine\Service\ObjectManagerService::getRepository
$resolvedEntityName = $this->getEntityManager()->getEntityClassByInterface($entityName);
в некоторых случаях надо получать репозиторий по имени конкретного класса, например определенный справочник(все справочники реализуют один и тот же интерфейс)

**Comment by old-town** [comment]
Реализовано в версии 0.1.21

**Comment by old-town** [comment]
Пример использования https://github.com/nnx-framework/doctrine/blob/0.1.22/test/phpunit/tests/Service/ObjectManagerServiceTest.php#L78
